# Site settings
title:       spin ½
email:       hi@amitjain.me
author:      Amit Jain
description: "spindump of thoughts and ideas"
baseurl:     ""
url:         "http://spinhalf.net"

# Google analytics
google_analytics:

# Optional features
animated:           true
show_related_posts: false
show_post_footers:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
show_social_icons: false
github_username: "gravicle"
stackoverflow_id:
twitter_username: "gravicle"
google_plus_id:
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
permalink: 		pretty
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     5
sass:
  compressed: true
